Library/Controllers/GuestController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Library.App_Data;

namespace Library.Controllers
{
    public class GuestController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Feedbacks = StaticDb.Feedbacks;
            
            return View();
        }

        [HttpGet]
        public ActionResult PostData(string name, string feedback)
        {
            return PostData(name, feedback, DateTime.Now);
        }

        [HttpPost]
        public ActionResult PostData(string name, string feedback, DateTime date)
        {
            StaticDb.Feedbacks.Add((StaticDb.Feedbacks.Last().Item1+1, name, feedback, date));
            
            return RedirectToAction("Index", "Guest");
        }
        
    }
}

Library/Controllers/HomeController.cs
using System.Web.Mvc;
using Library.App_Data;

namespace Library.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Articles = StaticDb.Articles;
            
            return View();
        }
    }
}

Library/Controllers/QuestionnaireController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Library.App_Data;

namespace Library.Controllers
{
    public class QuestionnaireController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.RadioAnswers = StaticDb.RadioAnswers;
            ViewBag.CheckAnswers = StaticDb.CheckAnswers;
            return View();
        }

        [HttpGet]
        public ActionResult QuestionnaireResult()
        {
            Console.WriteLine(Request.QueryString["radioReading"].Split(',').First());
            return QuestionnaireResult(Request.QueryString["Name"],
                Request.QueryString["radioReading"]?.Split(',').First(),
                Request.QueryString["checkBooks"]?.Split(','));
        }

        [HttpPost]
        public ActionResult QuestionnaireResult(string name, string reading, string[] books)
        {
            ViewBag.Name = name;

            ViewBag.Message = reading != "Don't read" ? "You are reading. It's great!!!" : "You are not reading. It's awful!!!";

            var userReading = StaticDb.RadioAnswers.FirstOrDefault(x => x.Item1 == reading);
            var indexOfReading = StaticDb.RadioAnswers.IndexOf(userReading);
            
            userReading.Item2++;
            
            StaticDb.RadioAnswers[indexOfReading] = userReading;

            if (books != null)
            {
                foreach (var book in books)
                {
                    var condition = StaticDb.CheckAnswers.Count(x => x.Item1 == book) == 1;

                    if (condition)
                    {
                        var userBook = StaticDb.CheckAnswers.FirstOrDefault(x => x.Item1 == book);
                        var indexOfBook = StaticDb.CheckAnswers.IndexOf(userBook);

                        userBook.Item2++;

                        StaticDb.CheckAnswers[indexOfBook] = userBook;  
                    }
                }
            }
            
            ViewBag.CheckAnswers = StaticDb.CheckAnswers; 
            ViewBag.RadioAnswers = StaticDb.RadioAnswers;

            return View();
        }
        
    }
}

Library/Views/Guest/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="col-sm-8">
    <div>
        @foreach (var article in ViewBag.Feedbacks)
        {
            <p>@article.Item3</p>
            <p>@article.Item4 - @article.Item2</p>
            <hr>
        }
    </div>
    <br>
    <div class="p-1">
        <h5 class="mb-2">For your opinions:</h5>
        @using (Html.BeginForm("PostData", "Guest", FormMethod.Get))
        {
            <input type="hidden" value="@ViewBag.Id" name="BookId"/>
            <div class="form-group">
                <label for="Name">Author`s name:</label>
                <input type="text" name="Name" id="Name" required class="form-control"/>
            </div>
            <div class="form-group"><label for="Feedback">Feedback:</label>
                <textarea rows="10" cols="45" name="Feedback" required id="Feedback" class="form-control"></textarea></div>
            <div class="form-group"><input type="submit" value="Send" class="form-control bg-dark text-white"></div>
        }
    </div>
</div>
<div class="col-sm-4">
    <ul class="nav nav-pills flex-column">
        <li class="nav-item">
            <a class="nav-link" href="/Home/Index">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="#">Guest</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Questionnaire/Index">Questionnaire</a>
        </li>
    </ul>
    <hr class="d-sm-none">
</div>

Library/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="col-sm-8">
    <ul>
        @foreach (var article in ViewBag.Articles)
        {
            <h2>@article.Item2</h2>
            <h5>@article.Item3</h5>
            <div class="fakeimg">Fake Image</div>
            <p>@article.Item4</p>
        }
    </ul>
</div>
<div class="col-sm-4">
    <ul class="nav nav-pills flex-column">
        <li class="nav-item">
            <a class="nav-link active" href="#">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Guest/Index">Guest</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Questionnaire/Index">Questionnaire</a>
        </li>
    </ul>
    <hr class="d-sm-none">
</div>
   

Library/Views/Questionnaire/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="col-sm-8">
    @using (Html.BeginForm("QuestionnaireResult", "Questionnaire", FormMethod.Get))
    {
        <div class="form-group">
            <h5 class="m-0 pb-2">Your name:</h5>
            <input type="text" required size="30" maxlength="30" name="Name" id="Name" class="form-control"/>
        </div>
        <div class="form-group">
            <h5 class="m-0 pb-2">How often do you read books?</h5>
            <div class="form-check pl-4">
                @foreach (var answer in ViewBag.RadioAnswers)
                {
                    <input required class="form-check-input" type="radio" name="radioReading" id="@answer.Item1" value="@answer.Item1">
                    <label class="form-check-label" for="@answer.Item1">@answer.Item1</label><br>
                }
            </div>
        </div>
        <div class="form-group">
            <h5 class="m-0 pb-2 mt-3">What books have you read?</h5>
            <div class="form-check pl-4">
                @foreach (var answer in ViewBag.CheckAnswers)
                {
                    <input class="form-check-input" type="checkbox" name="checkBooks" id="@answer.Item1" value="@answer.Item1">
                    <label class="form-check-label" for="@answer.Item1">@answer.Item1</label><br>
                }
            </div>
        </div>
        <div class="form-group mt-3">
            <input type="submit" value="Send" class="form-control bg-dark text-white">
        </div>
    }
</div>
<div class="col-sm-4">
    <ul class="nav nav-pills flex-column">
        <li class="nav-item">
            <a class="nav-link" href="/Home/Index">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Guest/Index">Guest</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="#">Questionnaire</a>
        </li>
    </ul>
    <hr class="d-sm-none">
</div>

Library/Views/Questionnaire/QuestionnaireResult.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="col-sm-8">
    <h5 class="m-0 pb-2">Thanks for your answer, @ViewBag.Name </h5>
    <p>@ViewBag.Message</p>

    <h5 class="m-0 mt-3 pb-2">Statistics of people reading:</h5>
    @ExtensionHelper.ListItems(Html, ViewBag.RadioAnswers)
    
    <h5 class="m-0 mt-3 pb-2">Statistics of most valuable books reading:</h5>
    @InlineHelper.OrderedList(ViewBag.CheckAnswers)
</div>

<div class="col-sm-4">
    <ul class="nav nav-pills flex-column">
        <li class="nav-item">
            <a class="nav-link" href="/Home/Index">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Guest/Index">Guest</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Questionnaire/Index">Questionnaire</a>
        </li>
    </ul>
    <hr class="d-sm-none">
</div>

Library/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.min.js"></script>
    <title>Document</title>
    <style>
        .fakeimg {
          height: 200px;
          background: #aaa;
        }
        </style>
</head>
<body>
    <nav class="navbar navbar-light bg-secondary">
        <a class="navbar-brand text-white" href="/Home/Index" id="#">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-book" viewBox="0 0 16 16">
                <path d="M1 2.828c.885-.37 2.154-.769 3.388-.893 1.33-.134 2.458.063 3.112.752v9.746c-.935-.53-2.12-.603-3.213-.493-1.18.12-2.37.461-3.287.811V2.828zm7.5-.141c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492V2.687zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783z"/>
            </svg>
            Library
        </a>
    </nav>

    <div class="container" style="margin-top:30px; max-width: 80%;">
        <div class="row">
            @RenderBody()
        </div>
      </div>

    <footer class="footer bg-secondary text-center pb-2">
        <p class="text-white p-2 m-0">&copy;Volodymyr Shenheliia, vladimir231200@gmail.com</p>
        <a class="text-red pb-2 m-0" href="#"><u>Link to start of the page</u></a>
    </footer>
</body>
</html>